services:
  monitor:
    build: .
    container_name: network_monitor
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    working_dir: /app
    command: python main.py
    restart: unless-stopped
